version: '3.8'

services:
  postgres:
    container_name: backend_postgres
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=userdata
    ports: 
      - 5432:5432
    